# Generated by Django 2.2.6 on 2019-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('age', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
