# Generated by Django 2.2.6 on 2019-10-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='phone',
            field=models.FloatField(),
        ),
    ]
