# Generated by Django 2.2.6 on 2019-10-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentData', '0003_auto_20191021_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='phone',
            field=models.FloatField(),
        ),
    ]
